language: node_js

env:
  - DB=postgresql://postgres@localhost:5432/registration_db_test;

node_js:
  - "12"

before_script: 
  - psql -c 'create database registration_db_test;' -U postgres
  - psql -U postgres -d registration_db_test -a -f reg.sql

addons:
  - postgresql